# Generated by Django 4.2.6 on 2023-10-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_globant', '0002_departments_jobs_hired_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
