# Generated by Django 4.2.6 on 2023-10-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_globant', '0003_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hired_employees',
            new_name='HiredEmployees',
        ),
    ]
